---
driver:
  name: docker
platforms:
  - name: debian-12
    image: geerlingguy/docker-debian12-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: debian-11
    image: geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: ubuntu-2404
    image: geerlingguy/docker-ubuntu2404-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: ubuntu-2204
    image: geerlingguy/docker-ubuntu2404-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    cgroupns_mode: host
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
